language: node_js
node_js:
  - "10"
  - "11"
before_install:
  - before_install:
      - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.5.1.deb && sudo dpkg -i --force-confnew elasticsearch-5.5.1.deb && sudo service elasticsearch restart
env:
  - NODE_TLS_REJECT_UNAUTHORIZED=0
services:
  - redis-server
script: "npm test"
before_script:
  - sleep 10
